### ISSUE TITLE
Generator: run ESLint on all source files

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/WC-Generator#157]
## Is your feature request related to a problem? Please describe.
ESLint currently only runs on files matching the pattern `src/[namespace]-*.js`. This excludes files that don't match that pattern, e.g. `util.js` and `component-base.js`. These files aren't included in the initial repo, but are added later and it's easy to miss those files.

We should be running on all JS source files for consistency.

## Describe the solution you'd like
We should run against files matching the pattern `src/*.js`.

## Describe alternatives you've considered
Do nothing.

## Additional context
I don't know if there was an existing reason why we didn't want to run against all JS files in src. Running against an existing repo (interruption) didn't raise any false positives.

**Comment by blackfalcon** [comment]
I initially did this because linters were having an issue with `*-css.js` files. But if that is not the case, I am all for this update. I see you did this with the auro-interruption CE.
