### ISSUE TITLE
Repo labels and label use policy

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#184]
## Is your feature request related to a problem? Please describe.

Labels are showing some age. 

## Describe the solution you'd like

Repository labels are a core part of Auro's communication of processes. The scope of the work here is to review all labels, review [label use policies](http://auro.alaskaair.com/contributing/issues-prs-labels), and ensure that the labels are being shown on the Auro docsite correctly reflect the actual labels in use with the Generator. 

Additional scope is to work with Auro's design support to have appropriate labels that reflect that work.

**Comment by blackfalcon** [comment]
Scope to consider: 

- [ ] adding a label for the name of the repo
- [ ] adding EPIC and STORY labels 
- [ ] When creating an auroLabs repo, all issue templates should have AuroLabs added to new issues

**Comment by geoffrich** [comment]
What is the value of adding a label with the name of the repo? Isn't that redundant since the issue/PR is already in that repository?

**Comment by blackfalcon** [comment]
The name of the element will be removed from the title. Doing so was a way to easier see what issue belongs to what repo in the Project view. 

Another value add is, labels allow for click-filter functionality in Project.

**Comment by blackfalcon** [comment]
Something that I want to consider is having a consistent policy for label use with each issue and pull request. 

1. What is the element/project?
2. What is the status of the issue or pull request?
3. What is the type of update? Bug, feature, etc...

**Comment by geoffrich** [comment]
I definitely find the current label structure confusing, and I'm never quite sure what labels I need to add. The more we can automate with this (e.g. each issue/PR automatically having the repo label attached), the better. I'm a heavy contributor to Auro, and I can barely keep track of which labels are necessary, so my guess is other contributors are in a similar (if not more confused) state.

I also think there's too many status labels at the moment. IMO, the essentials are
- In progress (applied to the issue when it's being worked on)
- Ready for review (only applied to the PR)
- Blocked

I think everything else can be conveyed by issue/PR state (e.g. open, closed, merged, etc). Having too many status labels means they won't get applied consistently.

Also, if possible, I think most labels (e.g. "type of update") should only be applied to the original issue. Also applying it to the PR is duplicative, and PRs are short-lived compared to their associated issues.

For all these suggestions, I'm speaking as a contributor to Auro. If it's not expected that I set most of these labels, then great, disregard my comments and label away! In the end, I want it to be clear what labels I am responsible to add, and I want to have to manually add as little labels as possible.

**Comment by blackfalcon** [comment]
I think with this we need to also review our new vX.x-rc policy when it comes to PRs. 

Issues are assigned to a RC milestone. Should PRs also be assigned too? 

IMHO, no. PRs are assigned to issues. Issues are assigned to milestones.

**Comment by braven112** [comment]
![image](https://user-images.githubusercontent.com/5118118/139498605-89e64246-9986-40ec-b380-5a1d8ebc1572.png)
