### ISSUE TITLE
Generator: option to throw exit code on build if not using latest version of a component

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/WC-Generator#189]
## Is your feature request related to a problem? Please describe.

As the maintainer of several repositories, the tooling available to me currently to validate my package.json dependencies are using latest from build-to-build involves a manual process of checking the Auro site against my dependencies manually. On build, all the auro packages output around 50 lines of ASCII art and block text about the version used, which in larger projects can be tough to scan through all auro dependencies individually to see their output.

## Describe the solution you'd like

A ciBuild option that would throw an exit code if a component is not matching the latest version in a build.

Even more useful would be if it didn't throw an exit code until after all dependencies were attempted to be resolved, because there can be many repositories out of date at once. Providing a list of out of date components and then exiting will fail pipelines similar to the eslint/stylelint steps. For auro components, this could happen in the commitlint step.

**Comment by geoffrich** [comment]
I wonder if [npm outdated](https://docs.npmjs.com/cli/v7/commands/npm-outdated) fits your use case? It won't fail the build, but it will show a list of all dependencies and what the latest version is.

Example from one of my projects:
```
Package                           Current  Wanted  Latest  Location
@alaskaairux/auro-button            5.1.2   5.3.1   6.3.4  disruptions-center-site
@alaskaairux/auro-icon              3.1.0   3.1.1   3.1.1  disruptions-center-site
@alaskaairux/auro-pane              1.1.1   1.1.2   1.1.2  disruptions-center-site
@alaskaairux/icons                  4.6.0   4.8.3   4.8.3  disruptions-center-site
@alaskaairux/ods-inputtext          1.0.8   1.1.1   1.1.1  disruptions-center-site
@alaskaairux/orion-design-tokens   2.12.2  2.12.3  2.12.3  disruptions-center-site
@alaskaairux/webcorestylesheets     3.2.0   3.6.2   3.6.2  disruptions-center-site
```

This won't capture the namespace (e.g. alaskaairux -> aurodesignsystem) or package name (ods-inputtext -> auro-input) changes, but hopefully that won't happen too often.

**Comment by blackfalcon** [comment]
@geoffrich beat me to it. I am not 100% sure what you are requesting @gusnaughton but what @geoffrich is pointing out is probably the best resource for out-of-date components. 

Also, he is right, any update that requires a new namespace for the next MAJOR version will not be listed here, but I am using what tools I have available to alert users of these MAJOR release updates.

**Comment by geoffrich** [comment]
It seems like `npm outdated` [returns an exit code of 1](https://npm.community/t/npm-outdated-should-have-an-option-to-have-non-zero-exit-code/10239) when there are outdated dependencies, and 0 when everything is up to date, so it could be used to fail the build if things are out of date.

However, this would apply to all deps, not just auro ones.

**Comment by blackfalcon** [comment]
Hearing no more about this issue, I am considering this closed.
