### ISSUE TITLE
Track component usage

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/WC-Generator#196]
This would help us determine what components are being used and what ones are not.  For things like AuroLabs this allows us to remove unused components.

1. We know how many times a component is rendered
2. What the URL is for that page.
3. How can we measure the impact a given component has.
4. What data do we already have
5. What data would be easy to get.

**Comment by blackfalcon** [comment]
This is probably the best way to find the information you are looking for https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository

The tricky part is going to be enabling the dependency graph for internal repos.

**Comment by braven112** [comment]
That would definitely help.  Another scenario to consider...what if component A depends on component B but component A is never actually used on a production page would that graph still show a dependency?  I'm assuming yes? 

I'd also like to figure out a way to know what pages our components are used on. I think it ties in really well with https://github.com/orgs/AlaskaAirlines/projects/16#card-68398737 If we know how often and where our components are it will be easier to deprecate old components or old versions or update to the latest version.  It will also help us prioritize defects if we know the impact.

**Comment by geoffrich** [comment]
Using [GH search](https://github.com/search?q=org%3AAlaska-Ecommerce+auro-button&type=code) can get you a nice idea of where things are being used, though it's a bit annoying to scroll through.

Maybe there's a way to use the GH API to keep track of all code references and expose somewhere?

**Comment by blackfalcon** [comment]
> I'd also like to figure out a way to know what pages our components are used on

@braven112 I see what you are shooting for, but I am not sure this is the right metric? I don't even know how we would be able to create that data? 

In regard to deprecation, knowing how much or how little a [thing] us used has no impact on a deprecation strategy. The point of that work is to alert users that an npm package version is no longer supported and provide next-step information. E.g. new version, different tool, etc...

**Comment by blackfalcon** [comment]
When speaking of prioritization, two factors that make sense to me are the scope of element and severity of the issue. 

For example, something like auro-hyperlink is much smaller in scope than auro-flight and is likely to be used way more. So when delivering an update to something small, there is always a wider impact and greater risk depending on the update. 

The prioritization of new feature work with Auro should be driven by the same principles as any other product. Who needs it and by when? Knowing that based on input provided by other teams will give us much greater insight into prioritization versus the gut-check we have now or the hot-button issue of the moment.

**Comment by braven112** [comment]
Great discussion!  I added this issue so we can discuss it at refinement tomorrow.

>  I see what you are shooting for, but I am not sure this is the right metric? I don't even know how we would be able to create that data?

What do you think the right metric is?  Getting the page name or URL should be easy enough but I have no idea how we would store it either.  Or what the performance impacts would be.  I just know the information would be helpful.  That's why I wrote it down so the team can explore the idea a bit.  

> So when delivering an update to something small, there is always a wider impact and greater risk depending on the update

Great example!  I'd rather avoid estimating how widespread a component is.  I'm sure it some cases it will seem obvious but in a lot of cases it would just be a semi educated guess.   The more data points we have the better decisions we can make.  

I'm also thinking about the longer term future of the generator.  There is also a fairly good chance that over time there will be unused components/repos.  AuroLabs is already a good example.

At the other end of the spectrum, there is tremendous value to the Auro team if we know the reach or impact of our most used components too, not just the unused ones.  Imagine if we had to make a business case for adding additional engineers or designers and the business has to decide between our team and other.  It certainly helps our case if we can show the impact our team has.

**Comment by blackfalcon** [comment]
> Getting the page name or URL should be easy enough...

I am interested in your proposal for this.

**Comment by braven112** [comment]
> > Getting the page name or URL should be easy enough...
> 
> I am interested in your proposal for this.

I was thinking of something like this to get the url `window.location.href`

I think most Alaska Pages would also have an utag object.  Though that method would probably only be useful if the component is on an ecommerce page in alaska, and wouldn't work with other non ecomm pages.
`window.utag_data = {
          page_name: ':home',
          channel: '',
          event: '',
          sitecore_version: 'aks',
        };`

**Comment by blackfalcon** [comment]
I am not familiar with how tags work in AScom, I need to be brought up to speed on this. How do you propose that this `utag` object is created? Is this something done on the page that is using components or is this in the component itself? 

If this is in the component itself, this was researched by @tsalright and myself [Lessons learned from building Tealium component](https://github.com/AlaskaAirlines/auro/blob/dad88fa8d66f853d7d81bf79e01db2764254e95e/src/discoveries/TEALIUM_LESSONS_LEARNED.md)

**Comment by braven112** [comment]
That's good info!  The utag method you mentioned is on a page level and its generally already created so I was just thinking that one method to get the page that the component is on is by reading that object but given that it would only work on a page that has tealium loaded its probably not the best solution for Auro components.

**Comment by blackfalcon** [comment]
Where I see issue with this line of thinking is that this adds a lot of overhead for the consuming engineer to tag the CEs for the purpose of our personal data collection. This will never be a priority and we will get pushback from others. I don't see that being a viable or trusted solution to get the data you are looking for.

**Comment by blackfalcon** [comment]
I still see a viable solution being what I outlined in a [previous comment](https://github.com/AlaskaAirlines/WC-Generator/issues/196#issuecomment-915550996). Between that and [npm weekly downloads](https://www.npmjs.com/package/@alaskaairux/auro-button) we can present good data about usage.

**Comment by braven112** [comment]
I'm

> Where I see issue with this line of thinking is that this adds a lot of overhead for the consuming engineer to tag the CEs for the purpose of our personal data collection. This will never be a priority and we will get pushback from others. I don't see that being a viable or trusted solution to get the data you are looking for.

I wasn't expecting consuming engineers to have to do anything.  I wanted to explore what info a component could collect without the consuming team having to do anything.

**Comment by braven112** [comment]
> I still see a viable solution being what I outlined in a [previous comment](https://github.com/AlaskaAirlines/WC-Generator/issues/196#issuecomment-915550996). Between that and [npm weekly downloads](https://www.npmjs.com/package/@alaskaairux/auro-button) we can present good data about usage.

The only potential blind spot was what @jason-capsule42 mentioned in that something like an auro-hyperlink may be used thousands of times but only be consumed by a finite number of components.
