### ISSUE TITLE
Tracking components idea

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/WC-Generator#211]
This is probably the best way to find the information you are looking for https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository

The tricky part is going to be enabling the dependency graph for internal repos.

_Originally posted by @blackfalcon in https://github.com/AlaskaAirlines/WC-Generator/issues/196#issuecomment-915550996_

**Comment by blackfalcon** [comment]
This was discovered 

> Dependents included
> For public repositories, only public repositories that depend on it or on packages that it publishes are reported. This information is not reported for private repositories.

So, that's a `no` on using the repos dependents insights to see what repos use any given element. 

That only leaves us with the idea that @geoffrich had about searching within the org. 
https://github.com/search?p=1&q=org%3AAlaska-ECommerce+auro-button+filename%3Apackage.json&type=Code

**Comment by blackfalcon** [comment]
Outside of a level of heroic work to create a new tracking service or piggy-backing on another service, we really are left with the search capability of Github to see the volume of use.

**Comment by blackfalcon** [comment]
@braven112 please see last comment. There is nothing else to be done here that I see.

**Comment by blackfalcon** [comment]
Transfering to @braven112 for closing out.
