### ISSUE TITLE
Minimum node version 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#217]
## Is your feature request related to a problem? Please describe.

With a recent update to a repo, it was discovered that pulling in MAJOR release versions of semantic-release packages requires a minimum of 14.17. 

Does this mean that we need to update WC-Generator to have a min of 14.17? 

https://github.com/AlaskaAirlines/WC-Generator/blob/3074b048d25b1e75409c724479f67e9d29f7c576/util/verifyNodeVersion.js#L34

## Describe the solution you'd like

Review policy for how we set minimum node version for WC-Generator

## Describe alternatives you've considered

The only other alternative is to allow the end-user to use an older version of Node, but then we set a trap that we need to document our way out of. 

## Additional context

This error is silent and does not break the build. So we can keep testing on 12 and up.

**Comment by geoffrich** [comment]
(posted this in teams, adding here for posterity)
Even though, the generator runs fine with Node 12, building/developing the generated component now requires Node 14.17.

I'm in favor of just requiring Node 14. What's the point in generating a new element without being able to develop it?

**Comment by blackfalcon** [comment]
Updated this to a `bug` as the current version of the WC-Generator will pull resources that require a higher version of Node than is listed as the minimum version.
