### ISSUE TITLE
Setting this to be true heavily restricts author's code

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#246]
IMHO, this should be set to `false`. 

https://github.com/AlaskaAirlines/WC-Generator/blob/0baeddedaa1ee07e7ed2418bdfd3bd4236b31248/template/.stylelintrc#L103

**Comment by geoffrich** [comment]
I agree. Seems like the rule is intended to keep specificity down, which has less relevance inside a shadow DOM. There are definitely valid use cases for using multiple pseudoclasses.
