### ISSUE TITLE
Generator: Document Refactor via markdown-magic.

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/WC-Generator#258]
Refactor documentation into smaller, more manageable, topic specific documents that can be compiled into other subjects.

Areas of concern:

## Content
- [x] Divide existing documentation in topic specific files
- [x] Create topic group files, e.g. "component install and usage" and "developing against this component"
- [ ] Integrate Table of Content and style doc pages as a two column layout

## Content Exposure / Publishing
- [ ] Update AuroDocSite for components updated with new doc structure

## Doc Generation Process
- [x] Integrate basic scripting of markdown-magic
- [ ] Refactor - move markdown-magic script to /scripts directory
- [ ] Integrate utility to create a comment-stripped version of the compiled docs for publishing

**Comment by blackfalcon** [comment]
**Suggestion**: The breaking down of content isn't really 100% topic-related, but they are simply partials to the whole. Can we rename the directory of `topics` to `partials` within the `./docs` dir? 

I feel that makes more sense.

**Comment by blackfalcon** [comment]
> Update AuroDocSite for components updated with new doc structure

I am not sure what that means? What specifically is needed to update in the docsite for this?

**Comment by blackfalcon** [comment]
**Automation**: Don't forget, the building of the md docs needs to be added to the `npm run dev` process as well included with the Github Action workflow and merged back to the repo with each version release.

**Comment by blackfalcon** [comment]
Should this issue be brought back for the work related to https://github.com/AlaskaAirlines/WC-Generator/pull/292 or should a new issue be written to support that work? 

@braven112 @jason-capsule42
