### ISSUE TITLE
Generator: npm run dev fails on Windows

### ISSUE THREAD

**Issue by Eliza-Huang** [AlaskaAirlines/WC-Generator#274]
## Describe the bug

The `npm run dev` command throws an error `'npm' is not recognized as internal or external command, operable program or batch file`

The fix is to use double quotes (right now it uses single quotes) in the `package.json` after we run the web component generator on line 165:
`"dev": "concurrently --kill-others \"npm run build:watch\" \"npm run serve\"",`

## To Reproduce

1. Make a component on Windows
2. Run `npm run dev` and you'll see an error

## Expected behavior

`npm run dev` will allow us concurrently run `npm run build:watch` and `npm run serve` without any errors.

## Screenshots

The error we see:
![image](https://user-images.githubusercontent.com/50314220/142301737-20437719-3ed0-4e3e-8f90-1f34fed9c493.png)

## Desktop (please complete the following information):
 - OS: Windows

## Smartphone (please complete the following information):
N/A

**Comment by blackfalcon** [comment]
Ahhhh Windows and their issues with quotes. Yup, I agree with the solution, it's much like what we had to do for 

```
"scssLint": "stylelint \"./src/**/*.scss\"",
```

Thanks for the feedback. Feel free to submit a PR or we will get to this as soon as we can.
