### ISSUE TITLE
Question about Docs

### ISSUE THREAD

**Issue by chadwtkns** [AlaskaAirlines/WC-Generator#282]
Sorry, I know this isn't the repo but after looking around I can't find which one would be the most appropriate one to raise this question to.  I've been looking around at the components you guys are building and they are really well done and would love to understand more how you guys are building your docs on https://auro.alaskaair.com/. So I'm curious if you guys have a repo that is generating your docs? If so could I ask what are you using to build out your docs? I do see that each component is generating some of the docs but I don't see where that overarching documentation lives. I appreciate the time taken to answer these if its at all possible. Thank you!

**Comment by blackfalcon** [comment]
@chadwtkns thanks for reaching out. 

The repo for the Auro doc site is an internal repo, so I can't share that with you. But I can share how it works. 

Simply put, it's a React site that, for the most part, renders markdown docs to HTML views. This is not unlike what we do with individual repos per element. 

https://github.com/AlaskaAirlines/WC-Generator/blob/3bdb2c90292d7353e9dfa0aae4d5bf660a487aa8/template/demo/index.html#L32-L41

This may not be the most performant thing, but it requires the least amount of maintenance. All the elements in the doc site are brought in via the pre-bundled versions we provide from a CDN with `@latest` as its version, and the individual markdown docs are all pulled from their repo. This allows us to simply release an update to anything and the doc site will be automatically updated. 

Additionally, we draw a log on Github's GraphQL data. Again, not awesome for performance, but for maintaining docs, this is a lifesaver. 

Hope that helps.

**Comment by chadwtkns** [comment]
Great. Thank you for sharing
