### ISSUE TITLE
Component build is setting wrong node version in github workflow

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/WC-Generator#288]
## Describe the bug

When building a component that is based on the 3.11.1 version of generator the .github/workflows/testPublish.yml is changing the release node-version from 16 to 14.

## To Reproduce

1. Go to your component
1. Update the component to v3.11.1 generator
1. `npm i`
1. `npm run build`
1. Look for changes in `.github/workflows/testPublish.yml`

## Expected behavior

testPublish.yml shouldn't have the node-version reverted to 14.

**Comment by blackfalcon** [comment]
I feel that there is something else happening here that is not that cut and dry. While I did not use a migration, I did run a build on dropdown and input which are both using v3.11 and from the build, the workflow.yml file was not updated. 

This leads me to suspect that if there is an issue, it happened in the migration process. Running a quick test now.

**Comment by jason-capsule42** [comment]
The branch I was on where this was occurring has sense been merged and deleted. I'm not able to reproduce it again. I know this was definitely happening *after* `npm run build`. In fact, earlier review comment pointed out the change in this file.

**Comment by blackfalcon** [comment]
https://github.com/AlaskaAirlines/WC-Generator/blob/bc1577a98719c1c3345cbc0b6fe146fb5a6e6476/template/.github/workflows/testPublish.yml#L40

That's the issue. It was missed that we are hardcoding the value. 

Hardcoded version should be replaced with `[abstractNodeVersion]`

This is not a HUGE issue as everything will run on 14 and 16, and the test prior to publish runs on the correct version pulled from the package.json. But this should be addressed. 

It's a `bug` for sure.

**Comment by blackfalcon** [comment]
@braven112 this is a super-small bug to address. Removed the `not-reviewed` label as @jason-capsule42 and I reviewed this together. 

Moved to `ready for work` for someone to pick up when open next.
