### ISSUE TITLE
generateDocs should use templates and target specific files to compile

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/WC-Generator#289]
## Describe the bug

the generateDocs script is not compatible with scripts that copy or move .md files (e.g. `npm run build:demo`) and should explicitly target the .md files we intend to compile.

## To Reproduce

1. Generate a new test repo
1. Go to the test repo
1. run `npm i`
1. run `npm run build:demo`
1. run `npm run build`

Note that because `generateDocs` is looking to compile all .md files in the root and child folders the copy of `demo.md` that was placed in /build breaks due to the path references in the file no longer being valid.

## Expected behavior

build:demo should be copying the already compiled version of demo.md so there is no need to recompile it.

generateDocs script should be updated to specifically target demo.md and readme.md rather than globally looking for any file to compile.

**Comment by blackfalcon** [comment]
I approve that this should be addressed as a `fix` and moved to `ready to work`

@braven112 what say you?

**Comment by braven112** [comment]
This one is done
