### ISSUE TITLE
Generator: stylelint rules need to use camelCase for ID and class

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/WC-Generator#290]
## Describe the bug

The following lines of code need to be added to the .stylelintrc file in the template

    "selector-class-pattern": "^[a-z][a-zA-Z0-9]+$",
    "selector-id-pattern": "^[a-z][a-zA-Z0-9]+$",

## Additional context

This issue is being addressed due to a discrepancy between the added StyleLint rules and the style guide already set forth with https://auro.alaskaair.com/css/conventions.

**Comment by blackfalcon** [comment]
@braven112 I am aware of this issue am cool with the proposed solution. I vote to remove `not-reviewed` and move this into `ready to work` column for someone to pick up.
