### ISSUE TITLE
Create a template for new blueprints

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/WC-Generator#295]
## Is your feature request related to a problem? Please describe.

- [ ] We want checklists for things that engineers need to review to validate that the blueprint matches what is released

https://github.com/AlaskaAirlines/auro-repo-template/issues/new/choose

**Comment by blackfalcon** [comment]
@braven112 this is really old... is this something that we still need to do? If so, I am not really clear as to the spec.

**Comment by leeejune** [comment]
@braven112 might have a better answer for this...

**Comment by blackfalcon** [comment]
> For new things we would use this one: [AlaskaAirlines/auro#266](https://github.com/AlaskaAirlines/auro/issues/266)

We have this https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/.github/ISSUE_TEMPLATE/blueprint.md

But we should also add it to this temp repo https://github.com/AlaskaAirlines/auro-repo-template/tree/main/.github/ISSUE_TEMPLATE

> And for our existing components that just need a figma component we would use this one:
> https://github.com/AlaskaAirlines/auro-avatar/issues/18

That is a case-by-case one and would have to be added individually.

**Comment by Patrick-Daly-AA** [comment]
From discussion with team, this is no longer needed.  @braven112 , please re-open if you feel otherwise.
