### ISSUE TITLE
Extract [npm], [name], [namespace] replacement code so it can be used by generateDocs.js

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/WC-Generator#300]
## Is your feature request related to a problem? Please describe.

Since we are now pulling static doc templates from the server we can no longer rely on a replacement process for all instances of [npm], [name], [namespace] to get replaced during the repo init.

The functions for this should be extracted from generate.js into a stand alone utility that can be referenced in generateDocs.js and executed each time the docs are regenerated.

As it stands today the readme.md file requires this to be done manually.

## Describe the solution you'd like

All functions for the content replacement should be in a class that can be imported used by any other script.

**Comment by blackfalcon** [comment]
This is an interesting wrinkle. 

> The functions for this should be extracted from generate.js into a stand alone utility that can be referenced in generateDocs.js

The issue with this is, we don't have the variable values in memory. 

I am wondering if it makes more sense to do a fetch of this content in the generator process itself versus waiting for mdmgk do to the work getting the static content? Maybe in the `copyAllFiles` function.  Then within the `copyFile` function the files would be available for the `formatTemplateFileContents` function. 

In the end, this content will be part of the reop's version control, right?

**Comment by jason-capsule42** [comment]
[namespace], [name] and [npm] can all be parsed from `package.json` `name` key.

**Comment by jason-capsule42** [comment]
> The issue with this is, we don't have the variable values in memory.

[namespace], [name] and [npm] can all be parsed from `package.json` `name` key.
