### ISSUE TITLE
Allow for customization of install content with markdown magic docs 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#322]
## Is your feature request related to a problem? Please describe.

The current setup is the following. 

1. With a build, the README file is generated from a template loaded into `docTemplates/README.md` that is pulled from `https://raw.githubusercontent.com/AlaskaAirlines/WC-Generator/master/componentDocs/README.md`
1. Within this template pulled from the remote on build, inner content for Install is pulled from `https://raw.githubusercontent.com/AlaskaAirlines/WC-Generator/master/componentDocs/partials/usage/componentInstall.md`

Because of this architecture, there is no way for a developer to customize any of the content around installation per an individual repo. 

## Describe the solution you'd like

Add a `peerDependcies.md` file that is referenced in the `./README.md` template.

## Exit criteria 

This issue will be considered complete once there is a defined process for adding peer dependencies to the install documentation.

**Comment by jason-capsule42** [comment]
The latest template has a custom section that is specifically there so that any custom non-standard information may be inserted into the readme.

https://raw.githubusercontent.com/AlaskaAirlines/WC-Generator/master/template/docs/partials/readmeAddlInfo.md

**Comment by geoffrich** [comment]
Can you give an example of what you want to customize about the README that you are unable to do with the current setup?

**Comment by blackfalcon** [comment]
Moving to a model where there are peer dependencies that need to be installed with the primary element. See the recently released https://auro.alaskaair.com/components/auro/select/install instructions. 

I am unable to edit the area under INSTALL, so I was forced to create an additional install instruction to alert the user of the additional peer deoendencies.

**Comment by jason-capsule42** [comment]
The original template was created before we started down the path of documenting peer dependencies in this way.

I want to keep the readme template common between components and expose areas for optional additional information like what was done with `readmeAddlInfo.md` file. This gives us the ability to assert that all components will have a base template of parts that must be present and no component would be able to remove those sections. 

I propose we add a `peerDependcies.md` file that is references in the readme.md template.

**Comment by blackfalcon** [comment]
> I propose we add a peerDependcies.md file that is referenced in the readme.md template.

Ok, I can get on board with that. I will update the scope of this issue and exit criteria.
