### ISSUE TITLE
EsLint Plugin Lit A11y

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#325]
## Is your feature request related to a problem? Please describe.

There is already some baseline a11y testing that we support with our unit tests. Can we be better? 

## Describe the solution you'd like

Review https://open-wc.org/docs/linting/eslint-plugin-lit-a11y/overview/

Will this add value to our current scenario? 

## Describe alternatives you've considered

Not use this new library and stick with what we have.

**Comment by geoffrich** [comment]
This is already in the Auro eslint config - see https://github.com/AlaskaAirlines/eslint-config-auro/issues/2.

https://github.com/AlaskaAirlines/eslint-config-auro/blob/8a9dfc6a42f4e56e6e7fdf59ea82e1ef9d02b250/.eslintrc.js#L10
