### ISSUE TITLE
Review Accessible-color-palettes for use with Figma docs 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#326]
## Is your feature request related to a problem? Please describe.

Accessible colors is paramount to maintain in all the work we do. We need to have a system of checks in the design process to ensure that we are using color correctly. 

## Describe the solution you'd like

Review the following tool for opportunity with out Figma blueprint docs. 

https://www.figma.com/community/plugin/970405419734718732/Accessible-color-palettes

## Describe alternatives you've considered

Hope that people get things right...

**Comment by leeejune** [comment]
@blackfalcon Is this about evaluating our blueprints/components? Or for making general design decisions for all designers? Designers actually use a similar plugin in Figma to evaluate color accessibility (called Contrast)!

**Comment by blackfalcon** [comment]
The intent of this request is to evaluate a tool to ensure that 100% of Auro UIs meet our a11y spec. If not this tool, then please suggest another. 

The goal is to standardize a tool to ensure compliance with all Auro own designs. 

While other designers may follow our lead, the intent is not to dictate a tool to other teams. Although, the conversation needs to be had, what are designers on the floor doing to ensure that their non-Auro UIs are 100% compliant?

**Comment by leeejune** [comment]
The tool "Contrast" is essentially the same tool.

I can integrate this tool for creating our components, but I also am aware that our color tokens have already passed accessibility tests (the UI tokens).

The designers are currently using similar tools (like "Contrast) to check accessibility on their designs. I don't think they check every single thing, but they do check text contrast, background contrast, and contrast on important interactions. I think there is also a sense of trust that our Auro color tokens have passed these accessibility tests.

**Comment by blackfalcon** [comment]
The only thing Auro has done to ensure accessible colors is to provide clear contrast feedback to the individual color itself. 
https://auro.alaskaair.com/color/digital-palette

We have nothing in place that ensures that when colors are used that they are used correctly. That is at the designer level and my desire is to have all the designers on the same page to ensure that combinations are correct. This is not a critical issue, but things pop up from time to time. 

There are things we can do at the [component level](https://viljamis.com/2022/launching-nord-design-system/#:~:text=programmatically%20pick%20the%20right%20text%20color%20based%20on%20the%20contrast%20ratio) to ensure proper support, but I'd prefer to catch things upstream versus correcting at the last mile.
