### ISSUE TITLE
Generator: Remove auroLabs question during generate

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/WC-Generator#339]
## Describe the feature update

The concept of auroLabs is dead. Please remove all references from the building script. 

## To Reproduce

1. Run the generate script for a new component
1. Note the question regarding auroLabs

## Expected behavior

Since we no longer support auroLabs we should remove this question

## Exit criteria 

This issue will be considered closed once all references and content pertaining to support auroLabs has been removed from code and does not appear during the generate process. This includes all the forked code from the generate file itself and all forked documentation.

**Comment by blackfalcon** [comment]
I wouldn't call that a `bug`, it's a `feature update`. It still works. Do we want it? No. But it's not broken.
