### ISSUE TITLE
Reflected Attributes documentation

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/WC-Generator#348]
## Is your feature request related to a problem? Please describe.

Sometimes attributes in Svelte need to have a reflected attribute.  Its not obvious when someone should and shouldn't add the reflected property.

## Describe the solution you'd like

Update the demo code in the generator to use a CSS attribute that requires the property to be reflected in the Lit code. In the comments around this code, place a link to the documentation. https://auro.alaskaair.com/generator/best-practice#gsc.tab=0:~:text=Reflect%20properties%20to%20attributes

## Describe alternatives you've considered

Hope that people know of the existence of the document.

**Comment by geoffrich** [comment]
I assume the documentation you're referencing is https://auro.alaskaair.com/generator/best-practice?

**Comment by braven112** [comment]
Yes!  We wanted to make that more clear as to why its important, and link to that document in a comment in the code so we don't miss it or overlook it going forward.

**Comment by jason-capsule42** [comment]
This is already outlined in the new component template [JS file](https://github.com/AlaskaAirlines/WC-Generator/blob/bf40785e7e2e38e7636c7a6348747dc2c0ca89ba/template/src/%5Bnamespace%5D-%5Bname%5D.js#L33-L35).

I believe we can lose this issue.
