### ISSUE TITLE
Unable to create working surge demo

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/WC-Generator#373]
https://auro-datepicker-v1.surge.sh/demo/

Running surge agains the `rc-v1.0` branch results in a demo with the following error:

`Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../".`

**Comment by blackfalcon** [comment]
Transferred this issue to the generator as this is not only a problem with datepicker. The demo creation and distribution process has not been kept up well and there are abundant issues.
