### ISSUE TITLE
Generator: Support for generating a component that uses TypeScript

### ISSUE THREAD

**Issue by jeremeevans** [AlaskaAirlines/WC-Generator#379]
## Is your feature request related to a problem? Please describe.

My team prefers to use TypeScript for front-end development. The generator does not currently support that.

## Describe the solution you'd like

Add a template for TypeScript. This feature is dependent on the previous feature for refactoring the generator.

* Split the existing JavaScript template into multiple templates. Some of those templates will be valid for JavaScript and TypeScript, others will be specific to one language or the other.
* When a project is being generated, aggregate the templates required to build the given project based on the question answers.
* Step through those templates to build out the project to be generated.

## Describe alternatives you've considered

This is a housekeeping task.

## Additional context

Should use https://github.com/Alaska-ECommerce/rtf-component as reference, as it is set up to build web components using TypeScript.

**Comment by blackfalcon** [comment]
Addressed with the following issue

- https://github.com/AlaskaAirlines/WC-Generator/issues/374
