### ISSUE TITLE
SvelteKit - Pages cannot render Auro components

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/WC-Generator#393]
### Please verify the version of wc-generator you have installed

3.1.2

### Please describe the bug

With the following imports, any SvelteKit SSR page appears to be returning this error related to exports:
<img width="1436" alt="image" src="https://github.com/AlaskaAirlines/WC-Generator/assets/7005799/9c7026a4-76a1-4be7-afb3-8658c09bda25">

Impacted components I'm aware of:
Accordion
Button
Icon
Flight
Flightline
Datetime
Badge
Hyperlink
Alert

My understanding of the sveltekit internals is light, but if there's something obvious I'm missing, I'd appreciate the help. Otherwise, to me, this appears to be some kind of issue with how the index.js file unrolls the /dist folder in each component.

This error does not occur when rendering the same component in Storybook, and it does not matter if I have SSR or Preload enabled on my Sveltekit Page.

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

The imports should work as they do when used within Storybook.

### What browsers are you seeing the problem on?

Chrome

### Additional context

This repository is internal only. I can pair with anyone to demonstrate the issue.

### Exit criteria

I can import auro components in SvelteKit environments.

**Comment by gusnaughton** [comment]
To reproduce:

```
npm create svelte@latest my-app
cd my-app
npm install
npm i --save @aurodesignsystem/auro-button
```

In ```src/routes/+page.svelte```, add:

```    import '@alaskaairux/auro-accordion';```

run the following:
```npm run dev``` and visit the root page.

**Comment by blackfalcon** [comment]
Up to this point, we have not supported Svelte SSR. Project configurations passed off the need to SSR web components and loaded them in parallel with the rest of the project.
