### ISSUE TITLE
wc-generator: update "Recommended Use..." section of `demo.md` to use partials

### ISSUE THREAD

**Issue by Izook** [AlaskaAirlines/WC-Generator#406]
### Is your feature request related to a problem? Please describe.

We can make documentation updating smoother if we have the "## Recommended Use and Version Control` section of `demo.md` dependent on a partial and an apiExample file. Currently all new generated components are populated with the `custom-header` example which is not ideal.

### Describe the solution you'd like

The "Recommended Use and Version Control" section of `demo.md` is populated with a partial and apiExample that uses `custom-<tagname>` instead of `custom-header`.

### Additional context

I noticed this when generating the `auro-sidenav` component.

**Comment by blackfalcon** [comment]
I support this update.
