### ISSUE TITLE
Less aggressive browserslist

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/WC-Generator#41]
## Is your feature request related to a problem? Please describe.
Currently the default browserslist is set to "last 4 versions, > 1%, IE 11." This evaluates to the following browsers:

```
and_chr 85  
and_ff 79   
and_qq 10.4 
and_uc 12.12
android 81  
baidu 7.12  
bb 10       
bb 7        
chrome 85   
chrome 84   
chrome 83   
chrome 81   
edge 85     
edge 84     
edge 83     
edge 81     
firefox 80  
firefox 79  
firefox 78  
firefox 77  
ie 11
ie 10
ie 9
ie 8
ie_mob 11
ie_mob 10
ios_saf 13.4-13.7
ios_saf 13.3
ios_saf 13.2
ios_saf 13.0-13.1
ios_saf 12.2-12.4
kaios 2.5
op_mini all
op_mob 46
op_mob 12.1
op_mob 12
op_mob 11.5
opera 70
opera 69
opera 68
opera 67
safari 13.1
safari 13
safari 12.1
safari 12
samsung 12.0
samsung 11.1-11.2
samsung 10.1
samsung 9.2
```

This is way more browsers than we need to support. We do not support IE mobile, IE 8-10, or Opera, for instance. This bloats our build by including unnecessary CSS prefixes.

As a test, I removed the "last 4 versions" from the auro-button browserslist and ran a build. The output (non-minified) CSS was 26 lines less and over 1KB smaller when minified (7.47KB vs 8.61KB). This is due to removing unused prefixes like -webkit-box-shadow, -webkit-transform, -ms-transform, -o-text-overflow, -moz-user-select, -webkit-transition, -o-transition, -webkit-animation, and -webkit-box-sizing. 

## Describe the solution you'd like
We should identify the browsers we need to support and set the browserslist accordingly instead of including the last 4 versions of every browser. This should first be done in the generator and then all other components updated.

## Additional context
This doesn't appear to affect the transpiled Webpack output at all.

**Comment by blackfalcon** [comment]
I 100% agree @geoffrich. Although part of the problem is the lack of real browser support specification, so with this we went with the catch-all as not to make waves. As well, it is a common template. 

What is interesting to note is that Alaska has released a new official browser support page https://www.alaskaair.com/content/about-us/site-info/browser-info and this clearly states the following:

> We support recent versions of the browsers listed below. Newer versions are more secure, load faster and display better-looking pages.

Also, notice the lack of IE. 

I think what you are going for would be 

```
  "browserslist": [
    "last 2 version",
    "> 5% in US",
    "not IE 10",
    "not IE_Mob 10",
    "not IE_Mob 11"
  ],
```

Which outputs 

```
and_chr 85
and_ff 79
and_qq 10.4
and_uc 12.12
android 81
baidu 7.12
bb 10
bb 7
chrome 85
chrome 84
edge 85
edge 84
firefox 80
firefox 79
ie 11
ios_saf 14.0
ios_saf 13.4-13.7
ios_saf 13.3
ios_saf 12.2-12.4
kaios 2.5
op_mini all
op_mob 59
op_mob 12.1
opera 70
opera 69
safari 14
safari 13.1
samsung 12.0
samsung 11.1-11.2
```

**Comment by geoffrich** [comment]
That browserslist looks like it still has a lot of browsers we don't plan on supporting (e.g. opera mini). Could we do something like:
```
last 2 Chrome versions
last 2 iOS major versions
ie 11
last 2 Firefox versions
last 2 Edge versions
last 2 Safari major versions
```

That outputs the following, which seems much more reasonable:
```
chrome 83
chrome 81
edge 83
edge 81
firefox 76
firefox 75
ie 11
ios_saf 13.4
ios_saf 13.3
ios_saf 13.2
ios_saf 13.0-13.1
ios_saf 12.2-12.4
ios_saf 12.0-12.1
safari 13.1
safari 13
safari 12.1
safari 12
```

**Comment by blackfalcon** [comment]
Working with auro-button, here are the following bundle size results. 

Baseline
> 13248 auro-button__bundled.js

```
  "browserslist": [
    "last 2 version",
    "> 15% in US",
    "not IE 10",
    "not IE_Mob 10",
    "not IE_Mob 11"
  ],
```

> 13117 auro-button__bundled.js

```
  "browserslist": [
    "last 2 Chrome versions",
    "last 2 iOS major versions",
    "ie 11",
    "last 2 Firefox versions",
    "last 2 Edge versions",
    "last 2 Safari major versions"
  ],
```

> 12087 auro-button__bundled.js

Total savings, around 1k. Savings are good, but this feels pretty aggressive and exclusionary. Are the trade-offs correct?

**Comment by geoffrich** [comment]
I think the trade-offs are fine, since we're only using this to generate CSS prefixes. Worst case, the browser doesn't apply the CSS (which is almost always a progressive enhancement).

I diffed the auro-button CSS outputs of the 2 buttons and here's the prefixes that are being added:
- -moz-user-select 
- -webkit-transform
- -webkit-box-shadow
- -webkit-box-sizing
- -webkit-animation
- -webkit-transition

A quick perusal of caniuse indicates that most of these are not necessary for modern browsers. Most of the savings seem to come from removing -webkit-box-shadow, [which doesn't appear to need prefixes since 2011](https://caniuse.com/css-boxshadow). Even if we did miss one, they wouldn't break the component. I think the 1KB savings is worth it.

**Comment by geoffrich** [comment]
moz-user-select: Firefox <= 68 (Jul 2019)
webkit-transform: Chrome <= 35, Safari <= 8, Android <= 4.4.4 
webkit-box-shadow: Chrome <= 9, Safari <= 5, Android <= 3
webkit-box-sizing: Chrome <= 9, Safari <= 5, Android <= 3
webkit-animation: Chrome <= 42 (2015), Safari <= 8 (2014), Android <= 4.4.4
webkit-transition: Chrome <= 25, Safari <= 6, Android <= 4.3

(stats from caniuse)

Every prefix besides moz-user-select has had unprefixed support for at least 5 years. I think it's okay to stop adding them. Firefox is an evergreen browser and user-select is an enhancement, so we shouldn't stress about not adding it.

**Comment by blackfalcon** [comment]
The browserlist is also used for the webpack config in creating the bundled files. Removing IE 11 also reduces the bundle size. 

> 11364 auro-button__bundled.js

And agreed ... vendor prefixing is dead in the water. The vast majority of the issues there are in regards to features that webkit still release out of band with the standards group to support iOS. 

In the end, I am good with this recommendation.

**Comment by geoffrich** [comment]
Reopening the issue because we need to dig a little deeper.

**Comment by geoffrich** [comment]
My issues are twofold:
1. We are including 1KB of prefixes we might not need (at least on auro-button, other components could be less/more)
2. `last 2 versions` includes way too many browsers. If there's browsers we want to support that require prefixes, that's fine, but we should be explicit about what those browsers are instead of including the last 2 versions of every browser in caniuse.

The biggest offender for auro-button, -webkit-box-shadow, seems to be due to [the MDN data for Android webview](https://caniuse.com/mdn-css_properties_box-shadow_inset). However, the data seems suspect to me since it also says "Support unknown" and [the main caniuse entry for box-shadow](https://caniuse.com/mdn-css_properties_box-shadow_inset) doesn't mention it.

So, if you think my proposal doesn't include enough browsers? Let's add more to the list. But let's not blanket include the last two versions of every browser.

As a reminder, my proposal was
```
  "browserslist": [
    "last 2 Chrome versions",
    "last 2 iOS major versions",
    "ie 11",
    "last 2 Firefox versions",
    "last 2 Edge versions",
    "last 2 Safari major versions"
  ],
```

**Comment by geoffrich** [comment]
I'm also not opposed to leaving in some sort of percentage-based criterion to catch commonly-used browsers we missed, e.g. >1% in US.
