### ISSUE TITLE
wc-generator: we should add `data-demo-script="true"` attributes to demo to support surge

### ISSUE THREAD

**Issue by Izook** [AlaskaAirlines/WC-Generator#415]
### Is your feature request related to a problem? Please describe.

I have to manually add the `data-demo-script="true"` attribute to my demos to support the surge workflow. 

### Describe the solution you'd like

The `data-demo-script="true"` attribute should be automatically added to demos so that the default component supports the surge workflow.

**Comment by blackfalcon** [comment]
@Izook this issue is assigned to a PR, does that mean this work is in progress?

**Comment by Izook** [comment]
I just opened that PR to demonstrate what I mean by the issue, I didn't want to officially mark it as in-progress or work on it without prioritizing it
