### ISSUE TITLE
ESM loading error when using SSR

### ISSUE THREAD

**Issue by aesthetiques** [AlaskaAirlines/WC-Generator#427]
# General Support Request

## Context

After installing, then attempting to import an auro package into a pre-existing svelte project (`import "@aurodesignsystem/auro-datepicker";`), or a barebones project that we spun up(tested with auro-flight as well), we're getting the following error:
![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/25255197/40dbf4c1-a436-4aec-8ec3-005ec79d9d83)

## Your Environment

* Version used: Latest
* Browser Name and version: Chrome 117.0.5938.149
* Operating System and version (desktop or mobile): MacOS
* Link to your project: https://github.com/Alaska-ECommerce/flightsearch-lem-svelte/ 
* Test link to sveltekit barebones project: https://stackblitz.com/edit/sveltejs-kit-template-default-xkfsx3?description=The%20default%20SvelteKit%20template,%20generated%20with%20create-svelte&file=src%2Froutes%2FCounter.svelte,src%2Froutes%2FHeader.svelte&title=SvelteKit%20Default%20Template

**Comment by blackfalcon** [comment]
ESM issues have been updated across most elements. See this Discussion for more information 

- https://github.com/AlaskaAirlines/WC-Generator/discussions/502
