### ISSUE TITLE
WC-Generator: Unable to build generated components in Windows environment

### ISSUE THREAD

**Issue by avancealaska** [AlaskaAirlines/WC-Generator#44]
## Describe the bug
When running `npm run build` on a component generated trough WC-Generator, the build process errors out, like so:
```
> stylelint './src/*.css'

Error: No files matching the pattern "'./src/*.css'" were found.
```
It seems that stylelint is very picky about using double quotes when run from a Windows environment.

## To Reproduce
1. Boot up your Windows machine.
2. Generate an Auro component with WC-Generator (e.g. `wc-generate --name test`)
3. Navigate to the directory of the newly created component. (e.g. `cd ../auro-test`)
3. Run `npm run build`
4. See stylelint error mentioned above

## Expected behavior
The component should build successfully

## Desktop 
 - OS: Windows 10

## Additional context
Attempted on git bash and Powershell

**Comment by blackfalcon** [comment]
Installed the latest version of the generator and ran the script you provided. Diff ... I am on a Mac. 

```
(master) /auro-test$ npm run lint

> @alaskaairux/auro-test@0.0.0 lint /Users/dale.sande@alaskaair.com/src/auro/components/forks/auro-test
> npm-run-all cssLint test:yaml esLint


> @alaskaairux/auro-test@0.0.0 cssLint /Users/dale.sande@alaskaair.com/src/auro/components/forks/auro-test
> stylelint './src/*.css'


> @alaskaairux/auro-test@0.0.0 test:yaml /Users/dale.sande@alaskaair.com/src/auro/components/forks/auro-test
> yamllint .travis.yml

✔ YAML Lint successful.

> @alaskaairux/auro-test@0.0.0 esLint /Users/dale.sande@alaskaair.com/src/auro/components/forks/auro-test
> eslint src/auro-*.js
```

Unable to reproduce the error you are reporting. Can you provide the specific error you are seeing?
