### ISSUE TITLE
Update generator templates 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#458]
### Discussed in https://github.com/AlaskaAirlines/WC-Generator/discussions/457

<div type='discussions-op-text'>

<sup>Originally posted by **blackfalcon** January  9, 2024</sup>
As of Lit 2.0 it's been understood that LitElement web components will be supported inside common SSR environments. This discussion is for supporting the various updates needed to deliver this capability. </div>

## Scope

The scope of this issue is to update the various templates within the generator to either be ES6 compatible and/or remove them from this repo and place in the auro-library repo for easy distribution and versioned single-source-of-truth use. 

The `package.json` fill will also need to be updated to reference the lib resource versus the local resource as well as add the `type="module"` ES6 configuration. 

## Exit criteria 

This issue will be considered complete once all file references have been updated and a user can execute a new repo and build without issues.

**Comment by jordanjones243** [comment]
With this ticket, I want to emphasize that we need to update the `bundleUse.md` template to use the correct CDN links for the updated design tokens and WCSS.
