### ISSUE TITLE
DevX: Standard shorthand for this.shadowRoot

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/WC-Generator#56]
## Is your feature request related to a problem? Please describe.
`this.shadowRoot` is a repeatedly used reference and something we want to encourage contributors to take advantage of to manipulate the DOM directly and potentially minimize the number of temporary variables used.

## Describe the solution you'd like
Something done in the MOW codebase to reduce the amount of jquery syntax was cluttering up the codebase was to alias `$jQuery` to `alaska`. so that everything was on the same scope. It cleaned up the old javascript really effectively.

Shoelace-ui also does something like this to add some syntactic sugar to otherwise slightly more verbose syntax: https://github.com/shoelace-style/shoelace/blob/next/src/components/avatar/avatar.tsx#L15

## Describe alternatives you've considered
Something along the lines of Shoelace seems desirable. @Component and @Prop are pretty clean.

**Comment by blackfalcon** [comment]
Ok, can you give an example of how you see this being effective in a component?

**Comment by blackfalcon** [comment]
This issue is getting pretty old. @gusnaughton can you provide an example of what you would like to see or has the moment passed?
