### ISSUE TITLE
Doc site should preserve left nav active state for pages regardless of current tab

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/WC-Generator#65]
## Describe the bug
Currently the doc site only shows the active state for left nav items while visiting the default landing tab in the content.

## To Reproduce
1. Go to 'auro.alaskaair.com'
2. Click on any component in the left nav
3. Notice the active state in the left nav
4. Click on a different tab for that component (e.g. API)
5. Notice the active state in the left nav

## Expected behavior
Active state should persist regardless of what tab is being viewed

**Comment by jason-capsule42** [comment]
Wrong repo...

**Comment by blackfalcon** [comment]
Please do not manually close issues. An issue should be linked to its pull request. Once the pull request is merged, the PR and the Issue will be closed automatically.

**Comment by blackfalcon** [comment]
O_O 

> Wrong repo

It's easy to make this mistake. Instead of closing the issue, please [transfer](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) the issue.
