### ISSUE TITLE
Generator: postCSS for fallback CSS variables

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#66]
## Is your feature request related to a problem? Please describe.

See conversation https://github.com/AlaskaAirlines/WebCoreStyleSheets/pull/65#issuecomment-790998740

## Describe the solution you'd like

Let's discuss a direction for how to best address this need. The Sass function will be released, but that is not the ideal situation for building out custom elements where there is an expectation of automation. 

I am disappointed that the current postCSS `postcss-custom-properties` will not support this, so I am interested in discussing options for how Auro can support this feature.

**Comment by blackfalcon** [comment]
I added a group of people to this issue as I am very much open to opinions.

**Comment by geoffrich** [comment]
I think a PostCSS plugin would be ideal for this -- doing this all inline when writing components would be a pain. Forking the existing one is probably our best option. IDK if we want to create our own package for this or copy it into the generator directly.

We can eventually strip the IE11 fallback stuff out of our fork once we drop support.

**Comment by blackfalcon** [comment]
> We can eventually strip the IE11 fallback stuff out of our fork once we drop support.

Ahh @geoffrich you got confused as I did. This is not an IE fallback, this is a fallback in case the variable is not there. 

> I think a PostCSS plugin would be ideal for this

100% agree. I see the reasoning behind the author's rejection of the PR. So yeah, fork postcss-custom-properties, rip out all the stuff that postcss-custom-properties does, and create a really small plugin that does what we want it to do. 

postcss-custom-properties-fallback

**Comment by gusnaughton** [comment]
I like the idea of having this as a PostCSS plugin as well.

> The thing is, when we drop IE support, we will be dropping the use of postcss-custom-properties as that is no longer needed.

We're at least a year out from this (thinking of RAIN). It might make sense for us to ship with this current plan and revisit when we're actually at the point where we can drop PostCSS.

**Comment by blackfalcon** [comment]
I am closing this issue as the conversation around this has really just not happened.
