### ISSUE TITLE
Generator: upgrade from Karma to Web Test Runner

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#81]
# General Support Request

It appears that open-wc/testing-karma is deprecated and they suggest upgrading to [Web Test Runner](https://modern-web.dev/docs/test-runner/overview/)? 

What will it take to upgrade to Web test runner? What is the effort to upgrade legacy components? Do we even need to upgrade legacy elements? 

The scope of this update is to only upgrade the generator and decide what is the effort needed to upgrade legacy repos?

**Comment by blackfalcon** [comment]
This work should have a PR pointing to the new `next` branch prior to release.

**Comment by geoffrich** [comment]
Currently proving out the new test runner with auro-pane before integrating into the generator.

**Comment by blackfalcon** [comment]
DO NOT make a PR against ‘master’. Use the ‘next’ branch.
