### ISSUE TITLE
wc-generator: add Sass style guide enforcement tooling 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#83]
## Is your feature request related to a problem? Please describe.

Opening Auro development to a larger audience of people who will not go through a 'training' scenario first, we need to add support to ensure consistency of Sass development. 

## Describe the solution you'd like

Adopt a standard set of tooling that will assist in enforcing rules that are consistent with https://sass-guidelin.es/ and well play into the rules that are currently supported by https://auro.alaskaair.com/webcorestylesheets/linter

## Describe alternatives you've considered

* CSS comb
* Beautify
* Prettier
* And other options may apply

## Additional context

This update will coincide with https://github.com/AlaskaAirlines/WebCoreStyleSheets/issues/67

## Feature branch and pull request

This update will be added to the `next` feature release branch for the generator. DO NOT create a pull request to `master` and be sure to create your feature branch from `next`. 

## Exit Criteria 

This issue will be considered done when there is a working example of a supporting tool that will 'enforce' best practices for Auro CSS.

**Comment by jason-capsule42** [comment]
Looks like this was closed due to the PR being closed by mistake. Reopening until the PR is resolved.
