### ISSUE TITLE
Generator: preferred development setup

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/WC-Generator#89]
# General Support Request

Fact: more than 3/4 the support question the Auro teams gets are related to development environments. Especially Windows. 

## Support request

Create a document, "Preferred development environment" in the ./docs dir. 

## Possible Solution

Create a new document in the repo to be distributed to the doc site. This document will outline the baseline development environment setup needed for the Auro team to support questions for Windows and Mac. 

The statement needs to be clear that issues that fall outside these baseline instructions are harder to pin down and if cannot be reproduced by the Auro team, the issue will be dismissed. 

#### macOS

macOS is already Linux, so nothing to really say there. 

1. brew - to clean out all the baseline security configs that macOS locks down
1. nvm - it is preferred that dev use nvm on macOS so that node versioning and support is NOT in macOS restricted space

#### Windows

Windows Subsystem for Linux is a MUST! 

1. nodist is nothing but a constant source of issues 

## Context

System support issues are a sore spot as they are extremely complicated to solve and having to troubleshoot another system set up to get to a root issue can be a very lengthy and painful process.

**Comment by blackfalcon** [comment]
@geoffrich and @gusnaughton you are requested to help support the creation of this doc. @geoffrich you especially, as you are the primary expert (that I know of) for WSL..

**Comment by geoffrich** [comment]
I can work on a doc outlining the WSL setup steps.

**Comment by blackfalcon** [comment]
@geoffrich I have marked this issue as WIP. Please let me know when you think you may have a doc to review for this. 

@gusnaughton if you have any preferences on this issue please let me know.

**Comment by geoffrich** [comment]
I should have something ready early next week.

**Comment by blackfalcon** [comment]
Page added to docsite.
